### ISSUE TITLE
"porter build promote" generates runtime panic

### ISSUE THREAD

**Issue by qwrrty** [adobe-platform/porter#178]

**Comment by phylake** [comment]
This is an issue with the Go runtime. You'll notice there is no porter code in the stack trace. If I can get a reliable repro I'll open an issue

```
panic: runtime error: slice bounds out of range
goroutine 44 [running]:
panic(0xb1a6e0, 0xc42000e0e0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
bytes.(*Buffer).ReadFrom(0xc4201381c0, 0x1088e80, 0xc42002e130, 0xc420189688, 0x40da01, 0xc420189690)
    /usr/local/go/src/bytes/buffer.go:177 +0x24c
io.copyBuffer(0x1087a00, 0xc4201381c0, 0x1088e80, 0xc42002e130, 0x0, 0x0, 0x0, 0xc42023e0b8, 0x0, 0x0)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x1087a00, 0xc4201381c0, 0x1088e80, 0xc42002e130, 0xaba4e0, 0xc42023e060, 0xc420189790)
    /usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0xaba4e0, 0xc42023e060)
    /usr/local/go/src/os/exec/exec.go:253 +0x4d
os/exec.(*Cmd).Start.func1(0xc4204ee2c0, 0xc4203ae740)
    /usr/local/go/src/os/exec/exec.go:370 +0x27
created by os/exec.(*Cmd).Start
    /usr/local/go/src/os/exec/exec.go:371 +0x4db
```
